version: '3'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/dockerfiles/frontend.Dockerfile
    image: unstract/frontend
    container_name: unstract-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=development
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`frontend.unstract.localhost`) && !PathPrefix(`/api/v1`, `/deployment`)